name: tfsec Validation

on:
  pull_request:
    branches:
      - main
env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif